scheduler - remove p3 along with task preemption and killable node scheduling
twitter/scoot pull request #368
Opened 2018-04-11 16:13 UTC by dgassaway

scorch the earth, round 1

2018-04-11 16:38 UTC, ryancouto commented on sched/scheduler/task_scheduler_test.go
> +With 3 nodes, expect: scheduled Job3, Job2, Job1
Job 4 when one of those finishes?

2018-04-11 16:38 UTC, ryancouto commented on sched/scheduler/task_scheduler_test.go
>  	// Check for 5 P2, 3 P1, and 2 P0 tasks
Looks like this isn't accurate based on line 294

2018-04-11 16:38 UTC, ryancouto commented on sched/scheduler/task_scheduler_test.go
> +With 10 nodes: assign nodes for 5 P2, 3 P1, and 2 P0 tasks
ditto per line 294

2018-04-11 21:15 UTC, jasonbs10 commented on sched/scheduler/job_state.go
> +func (j *jobState) errorRunningTask(taskId string, err error) {
I believe this was a recent addition of mine that is meant to handle the case where worker goes offline/online and we abort the old run. So I think we still need this but you can verify if that sounds suspect.

2018-04-11 21:19 UTC, jasonbs10 commented on sched/scheduler/stateful_scheduler.go
> +var NodeScaleAdjustment = []float32{.05, .2, .75}
Let's adjust these to be a little more fair, it's too easy for p0 tasks to starve when everything seems to be high priority. Maybe .15, .3, .55? I'd like this rewritten or at least moved to a config file but I don't think you want to do that in this PR.

2018-04-11 21:25 UTC, jasonbs10 commented on sched/scheduler/stateful_scheduler.go
> -				} else if nodeSt.runningJob != jobID || nodeSt.runningTask != taskID {
I'm not entirely sure if this is just for P3. Do you think the if-statement above is sufficient to handle the node lost case?

2018-04-11 21:30 UTC, jasonbs10 commented on sched/scheduler/task_scheduler.go
> +				}).Info("Unable to assign, no free node for task")
Should this be a warn or err?

2018-04-11 21:34 UTC, jasonbs10 requested changes
Thanks! Glad to see this all scorched, not sure why I ever thought it'd be appropriate for someone to do P3... super urgent things bypass scoot at twitter anyway.

How bad was it modifying the tests?

2018-04-12 16:20 UTC, dgdonut commented on sched/scheduler/stateful_scheduler.go
> -				} else if nodeSt.runningJob != jobID || nodeSt.runningTask != taskID {
I was trusting the comment here stating that this section should only get hit in the P3 case, which would have already handled cleanup.

Assuming for a sec that this could be hit in the node lost case as well - would we want to return like this block was doing and skip cleanup? What would have done the cleanup?

2018-04-12 16:21 UTC, dgdonut commented on sched/scheduler/stateful_scheduler.go
> +var NodeScaleAdjustment = []float32{.05, .2, .75}
Will update, but yeah will skip a refactor here

2018-04-12 16:22 UTC, dgdonut commented on sched/scheduler/job_state.go
> +func (j *jobState) errorRunningTask(taskId string, err error) {
This bool was only set in the "if ta.running != nil" block, and that taskAssignment.running field was only ever set in the assign() function when we went to steal a node from killableTasks. With the removal of killable tasks there's not longer an entry point for this

2018-04-12 16:22 UTC, dgdonut commented on sched/scheduler/task_scheduler.go
> +				}).Info("Unable to assign, no free node for task")
will warn

2018-04-12 16:23 UTC, dgdonut commented
Tests were actually not bad at all, pretty straightforward. Worked after first edit - I did some negative testing to make sure they were doing stuff :)

2018-04-12 21:13 UTC, jasonbs10 commented on sched/scheduler/stateful_scheduler.go
> -				} else if nodeSt.runningJob != jobID || nodeSt.runningTask != taskID {
On second thought, let's trust the comment at face value.

That said, I think what's bothering me is the handling of jobState.numTimesTried if a node hiccups and comes back. We may need to keep the 'preempted' arg and set it to true if the nodeId is the same but the actual node object has been replaced.

2018-04-12 21:14 UTC, jasonbs10 commented on sched/scheduler/job_state.go
> +func (j *jobState) errorRunningTask(taskId string, err error) {
See other comment, I may have missed an edge case in my last fix, and we may still need this.

2018-04-17 18:05 UTC, dgassaway commented
Updated - is this what we are going for? Not sure about testing

2018-04-17 19:13 UTC, jasonbs10 approved these changes
We should play it safe with this release. My suggestion would be to run autosandbox in smf1 and then repurpose atla for a shadow version of autosandbox (I'm not sure if you need to disable phab/email notifications in order to accomplish this). Do you have something easier in mind?

2018-04-17 21:00 UTC, dgassaway commented
Following up w/ internal PR to pull in and manage release

2018-04-17 21:01 UTC, merged